spring.application.name=medvalt
spring.datasource.url=jdbc:mysql://localhost:3306/medvault
spring.datasource.username=root
spring.datasource.password=Mohanreddysomu@2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=ThisIsASuperLongRandomSecretKeyForHS256Algorithm123456